import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Acerca } from "../components/Acerca";
import { Nav } from "../components/Nav";
import { Proyectos } from "../components/Proyectos";
import { proyectos as proyectosData } from "../data";
import { animateScroll, Element } from "react-scroll";

import { Proyecto } from "../data";
import { GetStaticProps } from "next";

export default function Home({ proyectos }: { proyectos: Proyecto[] }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="contenedor ">
        <Element name="acerca">
          <Acerca />
        </Element>
        <Element name="proyectos">
          <Proyectos proyectos={proyectos} />
        </Element>
      </main>

      <Element name="footer">
        <footer className="mt-52 ">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>

          <button
            className="active"
            onClick={() => animateScroll.scrollToTop()}
          >
            Volver jajaja
          </button>
        </footer>
      </Element>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      proyectos: proyectosData,
    },
  };
};
